### GEOMETRY
/Geometry/NextTonScale/active_diam    260. cm
/Geometry/NextTonScale/active_length  260. cm
/Geometry/NextTonScale/fcage_thickn   1. cm
/Geometry/NextTonScale/ics_thickn     12. cm
/Geometry/NextTonScale/vessel_thickn  2. cm
/Geometry/NextTonScale/gas_temperature  300. kelvin
/Geometry/NextTonScale/gas_pressure     15. bar
/Geometry/NextTonScale/gas XeHe
/Geometry/NextTonScale/XePercentage 99.9
/Geometry/NextTonScale/helium_A 3

### GENERATOR
/Generator/MuonAngleGenerator/region MUONS
/Generator/MuonAngleGenerator/min_energy 1 GeV
/Generator/MuonAngleGenerator/max_energy 3000 GeV
/Generator/MuonAngleGenerator/angles_on false

### ACTIONS
/Actions/DefaultEventAction/energy_threshold 2.3 MeV


### PHYSICS (For fast Simulation)
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


### VERBOSITIES
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### JOB CONTROL
/nexus/random_seed 57230
###/nexus/persistency/hdf5 true
/nexus/persistency/start_id 250
/nexus/persistency/outputFile outputs/Muons.next
