### GEOMETRY
/Geometry/RegisterGeometry TON_SCALE


### GENERATOR
/Generator/RegisterGenerator NEUTRON_GENERATOR


### ACTIONS
/Actions/RegisterTrackingAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterSteppingAction DEFAULT
/Actions/RegisterRunAction DEFAULT


### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/PhysicsList/RegisterPhysics G4EmExtraPhysics
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics

/physics_lists/em/MuonNuclear true


### EXTRA CONFIGURATION
/nexus/RegisterDelayedMacro macros/physics/Xe137.mac
/nexus/RegisterMacro ./macros/NextTonNeutronsXeHe.config.mac