### GEOMETRY
/Geometry/NextTonScale/active_diam   200. cm
/Geometry/NextTonScale/active_length 200. cm
/Geometry/NextTonScale/fcage_thickn    1. cm
/Geometry/NextTonScale/ics_thickn     12. cm
/Geometry/NextTonScale/vessel_thickn   2. cm
#/Geometry/NextTonScale/gas_density    89. kg/m3
/Geometry/NextTonScale/gas_pressure 15 bar

/Geometry/NextTonScale/tank_visibility   false
/Geometry/NextTonScale/vessel_visibility true
/Geometry/NextTonScale/ics_visibility    true
/Geometry/NextTonScale/fcage_visibility  true

/Geometry/NextTonScale/gas XeHe
/Geometry/NextTonScale/percXe 99
/Geometry/NextTonScale/helium_A 3

### GENERATOR
#Neutron generator for cosmogenics

/Generator/NeutronGenerator/min_energy	1000000000 eV
/Generator/NeutronGenerator/max_energy 1000000010 eV
/Generator/NeutronGenerator/region FIELD_CAGE


### PHYSICS (For fast Simulation)
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false


### VERBOSITIES
#/control/verbose 2
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


### JOB CONTROL
/nexus/random_seed 1144
/nexus/persistency/hdf5 true
/nexus/persistency/eventType background
/nexus/persistency/outputFile NextTonNeutronXe1He3_1000000000_1000000010eV_4Data