### GEOMETRY
/Geometry/RegisterGeometry TON_SCALE

### GENERATOR
/Generator/RegisterGenerator LABMUON_GENERATOR

### ACTIONS
/Actions/RegisterTrackingAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterSteppingAction DEFAULT
/Actions/RegisterRunAction DEFAULT


### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4EmExtraPhysics
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/physics_lists/em/MuonNuclear true

/nexus/RegisterDelayedMacro /n/holylfs02/LABS/guenette_lab/software/next/nexus/nexus-neutron_muon_studies/macros/physics/Xe137.mac
/nexus/RegisterMacro /n/holylfs02/LABS/guenette_lab/users/lrogers/Winter/data/Helium3_01percent/Config/Muons-0000-MUONS.config.mac
